version: '3.8'

services:
  movies-api:
    image: movies-api:local
    container_name: movies-api
    hostname: movies-api-host
    environment:
      - NODE_ENV=production
      - MONGO_PORT=27017
      - MONGO_DATABASE_HOST=DNLM_DB_HOST
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=adminPassword123
      - DATABASE_NAME=DNLM_DB
      - API_PORT=7001
      - API_USER=movies_api_user
      - API_PASS=movies_api_pass
    ports:
    - 7001:7001
    depends_on:
      - mongo
    networks:
      - apidb

  mongo:
    image: mongo:5.0
    container_name: dnlm-db
    hostname: DNLM_DB_HOST
    ports:
      - 27001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminPassword123
      - MONGO_INITDB_DATABASE=DNLM_DB
    networks:
      - apidb
    volumes:
      - ./database/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

networks:
  apidb:
    name: tnlm-api-db-net
    driver: bridge
